### ISSUE TITLE
List of dependencies required to run

### ISSUE THREAD

**Issue by scanf** [petterreinholdtsen/noark5-tester#1]
What are the required dependencies to run this?

**Comment by petterreinholdtsen** [comment]
[Alexander Alemayhu]
> What are the required dependencies to run this?

I'm not quite sure, but suspect you should get far on Debian with python
and python-mechanize installed.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by scanf** [comment]
Thanks did not think of install the Debian package.
Tried using easy_install and pip and that did not work
well.

**Comment by petterreinholdtsen** [comment]
[Alexander Alemayhu]
> Thanks did not think of install the Debian package.
> Tried using easy_install and pip and that did not work
> well.

What could be changed to make it more obvious to you?  Updated README?
debian/control content?

I prefer to download stuff that can be reproducably built from source,
not random stuff downloaded from the web with no signature checking, and
it did not occur to me that easy_install and pip could be seen as an
alternative.

-- 
Happy hacking
Petter Reinholdtsen
