### ISSUE TITLE
Content-type is assumed to be present even for empty responses

### ISSUE THREAD

**Issue by ivaylomitrev** [petterreinholdtsen/noark5-tester#34]
In `recursiveHateoas`, there is a check of the content type:
```
ctype = res.getheader('Content-Type')
...
if -1 != ctype.find('application/json') and \
```

This assumes that the content type is always specified which is not the case for empty responses (the RFC does not require the header to be specified when there is no payload in the response).

Currently, when an empty response is encountered (for valid or invalid reasons), the following exception is thrown which terminates the execution:
```
'NoneType' object has no attribute 'find'
```

**Comment by petterreinholdtsen** [comment]
[ivaylomitrev]
> Currently, when an empty response is encountered (for valid or invalid
> reasons), the following exception is thrown which terminates the
> execution: ``` 'NoneType' object has no attribute 'find'

Yes, I ran into this too crash too, but had not yet discovered it was
due to empty responses.

Chapter 6 of N5TG state that the application/vnd.noark5+json
content-type is required ('skal brukes'), and the only exceptions
described in regarding uploads and downloads of files as well as
modifying instances (PATCH uses application/merge-patch+json).  It is an
argument for specifying Content-Type also for "empty content", and as
far as I know "" is not valid JSON.  A quick read of www.json.org could
not validate this, but
<URL: https://stackoverflow.com/questions/18419428/what-is-the-minimum-valid-json >
seem to agree that a zero length content is not valid JSON.

With that out of the way, the format of an empty file is a rather
philosofical question.  I guess the test should be changed to report
empty content as the issue in addition to the missing content-type.

Why do you want to return no content?

Anyway, I will modify runtest to keep going when it encounter no
Content-Type.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
Believed to be handled in d8b51cdc2959308622b3f79e1d830ba55e14ff7b.

**Comment by ivaylomitrev** [comment]
Thank you! I have no actual use case for returning an empty response. It was an error on our side that has already been fixed. I just encountered it this way.

**Comment by petterreinholdtsen** [comment]
[ivaylomitrev]
> Thank you! I have no actual use case for returning an empty
> response. It was an error on our side that has already been fixed. I
> just encountered it this way.

I got some input on Content-type for empty files, and was pointed to 
<URL: https://datatracker.ietf.org/doc/html/rfc2616#section-7.2.1 >
stating 'If the media type remains unknown, the recipient SHOULD treat
it as type "application/octet-stream".'  as HTTP is the base protocol
here, I believe we implicitly inherit this behaviour from RFC 2616 and
this the client is wrong for not handling a missing Content-Type header.

When that is said, it was observed that the polite thing to do was to
return the same content type as in non-empty results, and to at least
return one of the MIME types listed in the HTTP Accept header of the
request.

Just mentioning this here in case you are interested.  I consider the
issue handled in runtest. :)

-- 
Happy hacking
Petter Reinholdtsen
